import "dotenv/config";
import prisma from "../server/db/prisma.js";

async function main() {
  await prisma.sideQuest.deleteMany();
  await prisma.spawnPoint.deleteMany();
  await prisma.con.deleteMany();

  const spawnPoints = await prisma.spawnPoint.createMany({
    data: [
      {
        name: "Battle & Brew",
        category: "Gaming venue",
        neighborhood: "Sandy Springs",
        address: "1489 Dunwoody Village Pkwy, Sandy Springs, GA 30338",
        latitude: 33.9265,
        longitude: -84.3505,
        hours: "Mon-Thu 4pm-12am, Fri 4pm-2am, Sat 12pm-2am, Sun 12pm-12am",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784690432/fit-900-600_34692-entire-venue-room_cinel6.jpg",
        description: "Battle & Brew is Atlanta's premier gaming bar — a full-service restaurant and bar with over 100 classic and modern arcade games, pinball machines, and console setups. Whether you're here for the weekly Tekken tournament, a casual game night, or just great food and drinks, Battle & Brew is the spot where Atlanta's FGC and gaming community comes alive. 21+ after 9PM on weekends.",
      },
      {
        name: "Oxford Comics & Games",
        category: "Comics & cards",
        neighborhood: "Buckhead",
        address: "2855 Piedmont Rd NE, Atlanta, GA 30305",
        latitude: 33.8384,
        longitude: -84.3642,
        hours: "Mon-Sat 10am-8pm, Sun 12pm-6pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784690815/GarCXsuXQAAUl2H_lub76f.jpg",
        description: "Oxford Comics & Games has been a cornerstone of Atlanta's nerd community since 1974. One of the oldest comic book shops in the Southeast, Oxford carries an enormous selection of single issues, trade paperbacks, graphic novels, and tabletop games. The staff genuinely knows their stuff, weekly events keep the community tight, and the back issue bins are a treasure hunt every time.",
      },
      {
        name: "Matcha Cafe Maiko",
        category: "Boba & matcha",
        neighborhood: "Doraville",
        address: "5671 Buford Hwy NE, Doraville, GA 30340",
        latitude: 33.8986,
        longitude: -84.2915,
        hours: "Tue-Thu 11am-9pm, Fri 11am-10pm, Sat 10am-10pm, Sun 10am-8pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784692151/AHRPTWkwBwGuoXGOWPrTthywv9ezTViok7YW5ZhxHzZYQTN_apQoP1KCb4nb0ejY3OMEhdLcyJ5vtHEiFwLyTqIjrOPD7c2wHfCGJsXALZIfAd8SXekAaIo4HC1ZIK2UkZycwF4cimgA_s680-w680-h510-rw_zcep8n.webp",
        description: "Tucked along Buford Highway, Matcha Cafe Maiko is a cozy Japanese-inspired cafe specializing in ceremonial grade matcha drinks, lattes, and desserts. The aesthetic is soft, warm, and manga-adjacent — the kind of place where you can stay for hours with a good read and a bowl of matcha. Maiko hosts regular language exchange meetups and manga mornings, making it a natural gathering spot for Atlanta's Japanese culture community.",
      },
      {
        name: "Fluffy Fluffy",
        category: "Cute cafe",
        neighborhood: "Doraville",
        address: "5001 Buford Hwy NE, Doraville, GA 30340",
        latitude: 33.8942,
        longitude: -84.2923,
        hours: "Mon-Sun 12pm-10pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784691573/AHRPTWnAKGc087NOhicrtvE7_7InfY17ib4-oJIFd8SIr9nOoy7a24mA6JVemcdCLZJPjuufau-6Oo0JNoJlkQtOMaOEvZutQ4CbRxM7TlPf93AFEkwJPccZ3GMBQFOe5oNz8__Ru64x_jsm-PL3_s680-w680-h510-rw_cntcek.webp",
        description: "Fluffy Fluffy is a kawaii-inspired dessert cafe serving signature fluffy pancakes, crepes, and bubble tea. The space is pastel-perfect — great for photos, great for dates, great for showing up in cosplay. A beloved staple of the Buford Highway corridor and the broader Atlanta kawaii community, Fluffy Fluffy is a must-visit for anyone who takes their aesthetic seriously.",
      },
      {
        name: "Tokyo Kuma",
        category: "Kawaii shop",
        neighborhood: "Buford Highway",
        address: "5150 Buford Hwy NE, Doraville, GA 30340",
        latitude: 33.8958,
        longitude: -84.2918,
        hours: "Mon-Sat 11am-7pm, Sun 12pm-6pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784692238/AHRPTWmfswdE9AE4T0mt5Vou75Bid2DN3b5L5oPxubsT_5QK-4SNiPzV2C1tPytL0W4ToipY6ZnQ_qPLHHYhjGcMApSU6xp3SjmuV9CFX-6Mj74WtxdA2Qc-SXzmIGZLnm2Y_eF1bR6__s680-w680-h510-rw_uezlgu.webp",
        description: "Tokyo Kuma is a Japanese import shop and kawaii boutique carrying plushies, stationery, figures, snacks, and hard-to-find collectibles from Japan. If you're hunting for a specific Sanrio item, a Studio Ghibli figure, or just want to browse shelves of things that make you happy, Tokyo Kuma delivers. Staff are friendly, knowledgeable, and fellow fans — they get it.",
      },
      {
        name: "Giga-Bites Cafe",
        category: "Comics & cards",
        neighborhood: "Marietta",
        address: "1985 Cobb Pkwy SE, Marietta, GA 30060",
        latitude: 33.9382,
        longitude: -84.5218,
        hours: "Mon-Thu 11am-11pm, Fri-Sat 11am-1am, Sun 12pm-10pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784692576/P1130428_p4i11m.webp",
        description: "Giga-Bites Cafe is a full-service gaming cafe and event space in Marietta with an enormous floor plan, tons of gaming tables, and one of the most active event schedules in the Atlanta area. From Pokemon League and Friday Night Magic to D&D open tables and board game nights, if it's a tabletop or card game event, there's a good chance Giga-Bites has it on the calendar. Food and drinks available all day.",
      },
      {
        name: "Joystick Game Bar",
        category: "Gaming venue",
        neighborhood: "Old Fourth Ward",
        address: "427 Edgewood Ave SE, Atlanta, GA 30312",
        latitude: 33.7537,
        longitude: -84.3762,
        hours: "Mon-Fri 5pm-2am, Sat-Sun 2pm-2am",
        is_marta_accessible: true,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784692672/Joystick_SNP-7_dms3fd_dkutgg.jpg",
        description: "Joystick Game Bar is Inman Park's beloved retro arcade bar, packed wall-to-wall with classic arcade cabinets, pinball machines, and a full bar. The vibe is loud, fun, and unapologetically nerdy. MARTA accessible from the King Memorial station, Joystick is one of the most central and accessible nerd spots in the city. A natural home for cosplay meetups, game nights, and spontaneous hangs.",
      },
      {
        name: "My Parent's Basement",
        category: "Comics & cards",
        neighborhood: "Avondale Estates",
        address: "5 N Avondale Rd, Avondale Estates, GA 30002",
        latitude: 33.7706,
        longitude: -84.2699,
        hours: "Mon-Thu 12pm-10pm, Fri-Sat 12pm-12am, Sun 12pm-8pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784692727/AHRPTWmdm28JCyridnW1uo8c_UpzK3KsLkT3mfyunASIb_8v4cUirR5YL8nSX5B_MmpPCDZ_FnudFWBzO_Xw8gv9w3hPCxc5iHqr8xNeKmE8o5q0tvdMYPGN-bktADUgMHBfXcFKXUT8_xTsYh-l_s680-w680-h510-rw_xgceqx.webp",
        description: "My Parent's Basement is a community-focused game store in charming Avondale Estates, known for its warm atmosphere and dedicated regulars. The shop carries a solid selection of trading card games, tabletop RPGs, board games, and miniatures, with weekly events that feel more like hanging out with friends than attending a tournament. If you want a local game store with actual community, this is it.",
      },
      {
        name: "404 Esports",
        category: "Gaming venue",
        neighborhood: "Doraville",
        address: "6035 Peachtree Rd C223, Atlanta, GA 30360",
        latitude: 33.9012,
        longitude: -84.2841,
        hours: "Wed-Thu 5pm-12am, Fri 5pm-2am, Sat 12pm-12am, Sun 3pm-10pm, Mon 5pm-12am, Tue 5pm-10pm",
        is_marta_accessible: false,
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784721723/AHRPTWkVch2Iq44eEoxpokJwLmEULCcxTQhqgREEFRMooeNHodatd_p9dc9BHvTXq5RRs4_aj3CWGCvM4jzKX9yv2mj9mRb9GCs_ueMV2HcqYDU0UIC3hbKshAJhOSYlI4ImDzOmWWGspQ_s680-w680-h510-rw_avkxmu.webp",
        description: "404 Esports is Atlanta's dedicated esports arena and gaming lounge, bringing competitive gaming to the heart of Doraville. With high-end PCs, console setups, and a full event calendar covering everything from casual open play to organized tournaments, this is the spot for serious and casual players alike. Whether you're grinding ranked or just looking for a place to run sets with the community, 404 Esports has a seat for you.",
      },
    ],
  });

  console.log(`Created ${spawnPoints.count} spawn points`);

  const savedSpawnPoints = await prisma.spawnPoint.findMany({ orderBy: { id: "asc" } });

  await prisma.sideQuest.createMany({
    data: [
      {
        spawn_point_id: savedSpawnPoints[1].id,
        name: "Friday Night Magic — Standard",
        description: "Whether you're a seasoned planeswalker or just learning the basics, Friday Night Magic at Oxford Comics is the place to be. Show up with your standard deck, borrow one from the shop, or just come to watch and learn. The atmosphere is competitive but welcoming — everyone here was a beginner once. Prizes awarded to top finishers, and the shop stays open late so you can trade cards after the rounds wrap up.",
        date: "2026-08-01",
        time: "7:00 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "weekly",
        category: "Gaming",
        tags: "mtg,cards,tournament",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784693040/1_s6jbxl.webp",
      },
      {
        spawn_point_id: savedSpawnPoints[5].id,
        name: "Pokemon League — All Skill Levels",
        description: "Giga-Bites runs one of the friendliest Pokemon TCG leagues in Atlanta. Come as you are — loaner decks are available if you don't have your own, and the regulars here are genuinely happy to teach new players. Saturday league nights are casual and fun, with time to trade, battle, and hang out between matches. All ages and skill levels welcome.",
        date: "2026-08-02",
        time: "12:00 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "weekly",
        category: "Gaming",
        tags: "pokemon,cards,casual",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784693518/jpeg_wn1nzn.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[2].id,
        name: "Matcha and Manga Morning",
        description: "Start your Sunday right at Matcha Cafe Maiko. Bring whatever you're currently reading — shonen, slice of life, horror, romance, we don't discriminate — and settle in for a relaxed morning of matcha and manga. No agenda, no pressure. Just good drinks, good reads, and the kind of easy conversation that happens when you're all into the same things. First time? Grab a seat and someone will say hi.",
        date: "2026-08-02",
        time: "10:00 AM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "monthly",
        category: "Social",
        tags: "manga,matcha,chill",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784693652/1c8e045680c196fa6b195cd67b78f865_ggpgwt.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[6].id,
        name: "Cosplay Meetup at Joystick",
        description: "Between con seasons, cosplayers need somewhere to be. This casual meetup at Joystick Game Bar is that place. Come in cosplay, come in street clothes — either way you belong here. Show off your latest build, get feedback, trade tips on materials and techniques, or just vibe with people who get it. Joystick has great drinks and a wall full of arcade cabinets to keep things fun. No judging, no competition, just community.",
        date: "2026-07-19",
        time: "2:00 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: false,
        recurrence: null,
        category: "Cosplay",
        tags: "cosplay,casual,social",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784693852/e3bbdc_b7e49ae8319445f4b1fa1ef7d121bd86_mv2_hch3cw.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[0].id,
        name: "Tekken 8 Weekly — Warrior Wednesday",
        description: "Battle & Brew's Warrior Wednesday is the premier weekly Tekken 8 event in Atlanta. This is a competitive bracket with cash prizes for the top three — come ready to play. The level of play is high, but all skill levels are welcome to enter and level up. Spectating is free. Doors open at 7:30 PM, brackets start at 8:00 PM sharp. 21+ only. Full bar available. Win or lose, the post-tournament conversations are half the fun.",
        date: "2026-08-05",
        time: "8:00 PM",
        cost: 5.00,
        is_free: false,
        is_beginner_friendly: false,
        is_recurring: true,
        recurrence: "weekly",
        category: "Gaming",
        tags: "fgc,tekken,competitive",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784694166/images_c9jssq.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[2].id,
        name: "Japanese Language Exchange",
        description: "Whether you're a native Japanese speaker, a dedicated learner, or somewhere in between — this biweekly language exchange at Matcha Cafe Maiko is for you. The format is casual: pair up, switch languages, help each other out. Native speakers get English practice, learners get real conversation experience. Absolute beginners are welcome. Show up knowing hiragana, or show up knowing nothing. Someone at this table will meet you where you are.",
        date: "2026-07-19",
        time: "6:30 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "biweekly",
        category: "Language",
        tags: "japanese,language,social",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784694275/image00003-2-2-3-1-2-2_ty7vy1.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[5].id,
        name: "D&D Open Table — One Shot",
        description: "Never played Dungeons & Dragons? Perfect — this is exactly where you should start. Giga-Bites hosts a beginner-friendly one-shot adventure every few weeks: a self-contained story you can jump into without any prior experience. Pre-made characters are provided, rules will be explained at the table, and the DM is patient and fun. Bring your curiosity and a willingness to roll some dice. Sessions run about 3-4 hours.",
        date: "2026-08-06",
        time: "6:00 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: false,
        recurrence: null,
        category: "Tabletop",
        tags: "dnd,tabletop,beginner",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784694544/95f61f_0bde9ee195c94eba8c05b28ba5a28c94_mv2_wra5oo.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[1].id,
        name: "Pokemon Go Community Day",
        description: "Oxford Comics is the meetup point for Atlanta's Pokemon Go Community Day — the monthly event where rare Pokemon spawn in the wild and the whole city gets a little more electric. Group up here before heading out to the nearby park to maximize spawns, trade catches, and coordinate raids. All trainers welcome, from level 5 to level 50. Bring a portable charger, wear comfortable shoes, and get ready to walk.",
        date: "2026-08-08",
        time: "11:00 AM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "monthly",
        category: "Gaming",
        tags: "pokemon,mobile,outdoors",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784694670/2024_Pokemon_World_Championships_Event_Photo_6_zd37sv.jpg",
      },
      {
        spawn_point_id: savedSpawnPoints[3].id,
        name: "Anime Club at Fluffy Fluffy",
        description: "Fluffy Fluffy's monthly anime club is the coziest watch party in Atlanta. Each month the group picks a series, settles in with pancakes and boba, and watches together — no gatekeeping, no prerequisites, just a room full of people who love anime and good food. Come with your current obsession, leave with three new recommendations. First-timers are welcomed with open arms. Check the community board at Fluffy for the current season's pick.",
        date: "2026-08-09",
        time: "3:00 PM",
        cost: null,
        is_free: true,
        is_beginner_friendly: true,
        is_recurring: true,
        recurrence: "monthly",
        category: "Social",
        tags: "anime,social,kawaii",
        image_url: "https://res.cloudinary.com/h8yfcjvw/image/upload/v1784721937/anime-club-update-thanks-to-everyone-who-came-out-to-our-v0-bvxw9aoslwrf1_hlfa6h.jpg",
      },
    ],
  });

  console.log("Created 9 side quests");

  await prisma.con.createMany({
    data: [
      { name: "MomoCon 2026", start_date: "2026-05-21", end_date: "2026-05-24", venue: "Georgia World Congress Center", neighborhood: "Downtown Atlanta", size: "Large", type: "Anime & Gaming", ticket_url: "https://momocon.com" },
      { name: "DragonCon 2026", start_date: "2026-09-03", end_date: "2026-09-07", venue: "Multiple Downtown Hotels", neighborhood: "Downtown Atlanta", size: "Massive", type: "Sci-Fi, Fantasy and Gaming", ticket_url: "https://dragoncon.org" },
      { name: "Anime Weekend Atlanta 2026", start_date: "2026-11-19", end_date: "2026-11-22", venue: "Renaissance Waverly Hotel", neighborhood: "Cobb Galleria", size: "Mid-size", type: "Anime", ticket_url: "https://awa-con.com" },
      { name: "HeroesCon Atlanta 2026", start_date: "2026-12-05", end_date: "2026-12-06", venue: "Cobb Galleria Centre", neighborhood: "Cobb Galleria", size: "Small", type: "Comics and Artist Alley", ticket_url: null },
    ],
  });

  console.log("Created 4 cons");
  console.log("🍑 Seed complete!");
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (error) => { console.error(error); await prisma.$disconnect(); process.exit(1); });